import Head from "next/head";
import Link from "next/link";
import Auth from "@/components/Auth";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>GITHUB 2.0</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Auth />
      </main>
    </>
  );
}
